# Multi-Language NLP Text Classifier (Feature Engineering)
**Author:** Matheus Paixão  
**Domain:** Natural Language Processing (NLP) & Pattern Recognition  
**Stack:** Python, Scikit-Learn (SVM), Regex, Pandas

## 1. Problem Definition & Objectives
Given an arbitrary text input (sentence/phrase), build a pattern recognition model that extracts linguistic features to accurately identify the target language (**English**, **Spanish**, or **Portuguese**).

In [1]:
#
# amostras de texto em diferentes línguas
#
ingles = [
"Hello, how are you?",
"I love to read books.",
"The weather is nice today.",
"Where is the nearest restaurant?",
"What time is it?",
"I enjoy playing soccer.",
"Can you help me with this?",
"I'm going to the movies tonight.",
"This is a beautiful place.",
"I like listening to music.",
"Do you speak English?",
"What is your favorite color?",
"I'm learning to play the guitar.",
"Have a great day!",
"I need to buy some groceries.",
"Let's go for a walk.",
"How was your weekend?",
"I'm excited for the concert.",
"Could you pass me the salt, please?",
"I have a meeting at 2 PM.",
"I'm planning a vacation.",
"She sings beautifully.",
"The cat is sleeping.",
"I want to learn French.",
"I enjoy going to the beach.",
"Where can I find a taxi?",
"I'm sorry for the inconvenience.",
"I'm studying for my exams.",
"I like to cook dinner at home.",
"Do you have any recommendations for restaurants?",
]

espanhol = [
"Hola, ¿cómo estás?",
"Me encanta leer libros.",
"El clima está agradable hoy.",
"¿Dónde está el restaurante más cercano?",
"¿Qué hora es?",
"Voy al parque todos los días.",
"¿Puedes ayudarme con esto?",
"Me gustaría ir de vacaciones.",
"Este es mi libro favorito.",
"Me gusta bailar salsa.",
"¿Hablas español?",
"¿Cuál es tu comida favorita?",
"Estoy aprendiendo a tocar el piano.",
"¡Que tengas un buen día!",
"Necesito comprar algunas frutas.",
"Vamos a dar un paseo.",
"¿Cómo estuvo tu fin de semana?",
"Estoy emocionado por el concierto.",
"¿Me pasas la sal, por favor?",
"Tengo una reunión a las 2 PM.",
"Estoy planeando unas vacaciones.",
"Ella canta hermosamente.",
"El perro está jugando.",
"Quiero aprender italiano.",
"Disfruto ir a la playa.",
"¿Dónde puedo encontrar un taxi?",
"Lamento las molestias.",
"Estoy estudiando para mis exámenes.",
"Me gusta cocinar la cena en casa.",
"¿Tienes alguna recomendación de restaurantes?",
]

portugues = [
"Estou indo para o trabalho agora.",
"Adoro passar tempo com minha família.",
"Preciso comprar leite e pão.",
"Vamos ao cinema no sábado.",
"Gosto de praticar esportes ao ar livre.",
"O trânsito está terrível hoje.",
"A comida estava deliciosa!",
"Você já visitou o Rio de Janeiro?",
"Tenho uma reunião importante amanhã.",
"A festa começa às 20h.",
"Estou cansado depois de um longo dia de trabalho.",
"Vamos fazer um churrasco no final de semana.",
"O livro que estou lendo é muito interessante.",
"Estou aprendendo a cozinhar pratos novos.",
"Preciso fazer exercícios físicos regularmente.",
"Vou viajar para o exterior nas férias.",
"Você gosta de dançar?",
"Hoje é meu aniversário!",
"Gosto de ouvir música clássica.",
"Estou estudando para o vestibular.",
"Meu time de futebol favorito ganhou o jogo.",
"Quero aprender a tocar violão.",
"Vamos fazer uma viagem de carro.",
"O parque fica cheio aos finais de semana.",
"O filme que assisti ontem foi ótimo.",
"Preciso resolver esse problema o mais rápido possível.",
"Adoro explorar novos lugares.",
"Vou visitar meus avós no domingo.",
"Estou ansioso para as férias de verão.",
"Gosto de fazer caminhadas na natureza.",
"O restaurante tem uma vista incrível.",
"Vamos sair para jantar no sábado.",
]

## 2. Text Representation & Pattern Construction
Text samples are converted into feature vectors capturing language-specific morphological, orthographic, and syntactic properties.

In [2]:
import random

pre_padroes = []
for frase in ingles:
  pre_padroes.append( [frase, 'inglês'])

for frase in espanhol:
  pre_padroes.append( [frase, 'espanhol'])

for frase in portugues:
  pre_padroes.append( [frase, 'português'])

random.shuffle(pre_padroes)
print(pre_padroes)

[['Me gusta cocinar la cena en casa.', 'espanhol'], ['Hola, ¿cómo estás?', 'espanhol'], ['¿Cuál es tu comida favorita?', 'espanhol'], ['I like to cook dinner at home.', 'inglês'], ['O livro que estou lendo é muito interessante.', 'português'], ['Estou ansioso para as férias de verão.', 'português'], ['Gosto de ouvir música clássica.', 'português'], ['Vou viajar para o exterior nas férias.', 'português'], ['She sings beautifully.', 'inglês'], ['Preciso fazer exercícios físicos regularmente.', 'português'], ['Lamento las molestias.', 'espanhol'], ['Adoro passar tempo com minha família.', 'português'], ['Vamos ao cinema no sábado.', 'português'], ['Você já visitou o Rio de Janeiro?', 'português'], ["I'm planning a vacation.", 'inglês'], ['I like listening to music.', 'inglês'], ['What is your favorite color?', 'inglês'], ['¡Que tengas un buen día!', 'espanhol'], ['Where is the nearest restaurant?', 'inglês'], ["I'm sorry for the inconvenience.", 'inglês'], ['Estou estudando para o vestibu

## 3. Training Data Assembly
Phrases across English, Spanish, and Portuguese are aggregated into a structured DataFrame.

In [3]:
import pandas as pd
dados = pd.DataFrame(pre_padroes)
dados

,0,1
0,Me gusta cocinar la cena en casa.,espanhol
1,"Hola, ¿cómo estás?",espanhol
2,¿Cuál es tu comida favorita?,espanhol
3,I like to cook dinner at home.,inglês
4,O livro que estou lendo é muito interessante.,português
...,...,...
87,Me gusta bailar salsa.,espanhol
88,El clima está agradable hoy.,espanhol
89,Meu time de futebol favorito ganhou o jogo.,português
90,I need to buy some groceries.,inglês


## 4. Feature Extraction Pipeline
Engineering 17 distinct linguistic features using Regular Expressions (Regex):
- Average word length
- Spanish inverted punctuation (, )
- Language-specific character indicators (, )
- Language suffixes ( vs. )
- English contractions ()
- Stopword frequency distributions
- Accent mark counters (, , , , , , )

In [31]:
# a entrada é o vetor pre_padroes e a saída desse passo deverá ser "padrões"
import re

def tamanhoMedioFrases(texto):
  palavras = re.split("\s",texto)
  #print(palavras)
  tamanhos = [len(s) for s in palavras if len(s)>0]
  #print(tamanhos)
  soma = 0
  for t in tamanhos:
    soma=soma+t
  return soma / len(tamanhos)

def has_spanish_inverted_punctuation(texto):
    return 1.0 if re.search(r"[¿¡]", texto, re.UNICODE) else 0.0

def has_cedilla(texto):
    return 1.0 if 'ç' in texto else 0.0

def has_enie(texto):
    return 1.0 if 'ñ' in texto else 0.0

def has_portuguese_suffix(texto):
    return 1.0 if texto.lower().endswith('ção') else 0.0

def has_spanish_suffix(texto):
    return 1.0 if texto.lower().endswith('ción') else 0.0

def has_english_contraction(texto):
    import re
    return 1.0 if re.search(r"\b\w+'\w+\b", texto) else 0.0

def contains_common_english(texto):
    import re
    return 1.0 if re.search(r"\b(the|how|is|and)\b", texto, re.IGNORECASE) else 0.0

def contains_common_spanish(texto):
    import re
    return 1.0 if re.search(r"\b(el|la|que|de|y)\b", texto, re.IGNORECASE) else 0.0

def contains_common_portuguese(texto):
    import re
    return 1.0 if re.search(r"\b(que|não|por|para)\b", texto, re.IGNORECASE) else 0.0

def count_portuguese_accents(texto):
    return sum(texto.count(c) for c in ['ã', 'õ', 'â', 'ê', 'ô', 'á', 'é', 'í', 'ó', 'ú', 'ç'])

def count_spanish_accents(texto):
    return sum(texto.count(c) for c in ['á', 'é', 'í', 'ó', 'ú', 'ñ'])

def count_tildes(texto):
    return texto.count('ñ') + texto.count('ã') + texto.count('õ')

def contains_spanish_articles(texto):
    import re
    return 1.0 if re.search(r'\b(el|la|los|las|un|una|unos|unas)\b', texto, re.IGNORECASE) else 0.0

def contains_portuguese_articles(texto):
    import re
    return 1.0 if re.search(r'\b(o|a|os|as|um|uma|uns|umas)\b', texto, re.IGNORECASE) else 0.0

def contains_spanish_question_words(texto):
    return 1.0 if any(p in texto.lower() for p in ['¿qué', '¿dónde', '¿cuál', '¿cómo']) else 0.0

def contains_portuguese_question_words(texto):
    return 1.0 if any(p in texto.lower() for p in ['o que', 'onde', 'qual', 'como']) else 0.0

def y_ratio(texto):
    import re
    words = re.findall(r"\b\w+\b", texto.lower())
    if not words: return 0.0
    return sum(1 for w in words if 'y' in w) / len(words)

def extraiCaracteristicas(frase):
  # frase é um vetor [ 'texto', 'lingua' ]
  texto = frase[0]
  pattern_regex = re.compile('[^\w+]', re.UNICODE)
  texto = re.sub(pattern_regex,' ',texto)
  #print(texto)
  caracteristica1=tamanhoMedioFrases(texto)
  caracteristica2=has_spanish_inverted_punctuation(texto)
  caracteristica3=has_cedilla(texto)
  caracteristica4=has_enie(texto)
  caracteristica5=has_portuguese_suffix(texto)
  caracteristica6=has_spanish_suffix(texto)
  caracteristica7=has_english_contraction(texto)
  caracteristica8=contains_common_english(texto)
  caracteristica9=contains_common_spanish(texto)
  caracteristica10=contains_common_portuguese(texto)
  caracteristica11=count_portuguese_accents(texto)
  caracteristica12=count_spanish_accents(texto)
  caracteristica13=count_tildes(texto)
  caracteristica14=contains_spanish_articles(texto)
  caracteristica15=contains_spanish_question_words(texto)
  caracteristica16=contains_portuguese_question_words(texto)
  caracteristica17=contains_portuguese_articles(texto)

  # acrescente as suas funcoes no vetor padrao
  padrao = [valor for nome, valor in locals().items() if nome.startswith("caracteristica")]
  padrao.append(frase[1])  # adiciona o rótulo ao final

  return padrao

def geraPadroes(frases):
  padroes = []
  for frase in frases:
    padrao = extraiCaracteristicas(frase)
    padroes.append(padrao)
  return padroes

# converte o formato [frase classe] em
# [caracteristica_1, caracteristica_2,... caracteristica n, classe]
padroes = geraPadroes(pre_padroes)

#
# apenas para visualizacao
print(padroes)

dados = pd.DataFrame(padroes)
dados

[[3.7142857142857144, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0, 0, 0, 1.0, 0.0, 0.0, 0.0, 'espanhol'], [4.333333333333333, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 2, 2, 0, 0.0, 0.0, 0.0, 0.0, 'espanhol'], [4.4, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1, 1, 0, 0.0, 0.0, 0.0, 0.0, 'espanhol'], [3.2857142857142856, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0, 0, 0, 0.0, 0.0, 0.0, 0.0, 'inglês'], [4.625, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1, 1, 0, 0.0, 0.0, 1.0, 1.0, 'português'], [4.428571428571429, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 2, 1, 1, 0.0, 0.0, 0.0, 1.0, 'português'], [5.2, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 2, 2, 0, 0.0, 0.0, 0.0, 0.0, 'português'], [4.428571428571429, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1, 1, 0, 0.0, 0.0, 0.0, 1.0, 'português'], [6.333333333333333, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0, 0, 0, 0.0, 0.0, 0.0, 0.0, 'inglês'], [8.2, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 2, 2, 0, 0.0, 0.0, 0.0,

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17
0,3.714286,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0,0,0,1.0,0.0,0.0,0.0,espanhol
1,4.333333,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2,2,0,0.0,0.0,0.0,0.0,espanhol
2,4.400000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,1,0,0.0,0.0,0.0,0.0,espanhol
3,3.285714,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0.0,0.0,0.0,0.0,inglês
4,4.625000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1,1,0,0.0,0.0,1.0,1.0,português
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87,4.500000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0.0,0.0,0.0,0.0,espanhol
88,4.600000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,1,0,1.0,0.0,0.0,0.0,espanhol
89,4.375000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0,0,0,0.0,0.0,0.0,1.0,português
90,3.833333,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0.0,0.0,0.0,0.0,inglês


## 5. Model Training & Train-Test Partitioning
Splitting dataset into 75% Training and 25% Test sets with stratified sampling.

In [32]:
from sklearn.model_selection import train_test_split
import numpy as np


#from sklearn.metrics import confusion_matrix

vet = np.array(padroes)
classes = vet[:,-1]         # classes = [p[-1] for p in padroes]
#print(classes)
padroes_sem_classe = vet[:,0:-1]
#print(padroes_sem_classe)
X_train, X_test, y_train, y_test = train_test_split(padroes_sem_classe, classes, test_size=0.25, stratify=classes)


## 6. Model Evaluation (Support Vector Machine)
Evaluating SVM classifier performance using Confusion Matrix and Classification Metrics.

In [33]:
from sklearn import svm
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

treinador = svm.SVC()  #algoritmo escolhido
modelo = treinador.fit(X_train, y_train)

#
# score com os dados de treinamento
acuracia = modelo.score(X_train, y_train)
print("Acurácia nos dados de treinamento: {:.2f}%".format(acuracia * 100))

#
# melhor avaliar com a matriz de confusão
y_pred = modelo.predict(X_train)
cm = confusion_matrix(y_train, y_pred)
print(cm)
print(classification_report(y_train, y_pred))

#
# com dados de teste que não foram usados no treinamento
print('métricas mais confiáveis')
y_pred2 = modelo.predict(X_test)
cm = confusion_matrix(y_test, y_pred2)
print(cm)
print(classification_report(y_test, y_pred2))


Acurácia nos dados de treinamento: 88.41%
[[19  2  1]
 [ 1 22  0]
 [ 4  0 20]]
              precision    recall  f1-score   support

    espanhol       0.79      0.86      0.83        22
      inglês       0.92      0.96      0.94        23
   português       0.95      0.83      0.89        24

    accuracy                           0.88        69
   macro avg       0.89      0.88      0.88        69
weighted avg       0.89      0.88      0.88        69

métricas mais confiáveis
[[5 2 1]
 [1 6 0]
 [4 0 4]]
              precision    recall  f1-score   support

    espanhol       0.50      0.62      0.56         8
      inglês       0.75      0.86      0.80         7
   português       0.80      0.50      0.62         8

    accuracy                           0.65        23
   macro avg       0.68      0.66      0.66        23
weighted avg       0.68      0.65      0.65        23

